version: "3"

services:
  dlite_entities_service:
    build:
      context: "."
      target: "${entity_service_docker_target:-development}"
    ports:
      - "${PORT:-8000}:80"
    environment:
      entity_service_base_url: "http://onto-ns.com/meta"
      entity_service_mongo_uri: "mongodb://mongodb:27017"
      entity_service_mongo_user: ${MONGO_USER:-root}
      entity_service_mongo_password: ${MONGO_PASSWORD:-root}
    depends_on:
      - mongodb
    networks:
      - dlite_entities_net
    volumes:
      - "${PWD}:/app"

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-root}
    networks:
      - dlite_entities_net

networks:
  dlite_entities_net:
