[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "dlite_entities_service"

[project]
name = "dlite-entities-service"
authors = [
    {name = "Casper Welzel Andersen", email = "casper.w.andersen@sintef.no"},
]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Private :: Do Not Upload",
]
keywords = ["dlite", "mongodb"]
requires-python = "~=3.10"
dynamic = ["version", "description"]

dependencies = [
    "fastapi ~=0.95.0",
    "pymongo ~=4.3",
    "python-dotenv ~=1.0",
    "uvicorn >=0.21.1,<1",
]

[project.optional-dependencies]
# docs = [
#     "mike ~=1.1",
#     "mkdocs ~=1.4",
#     "mkdocs-awesome-pages-plugin ~=2.8",
#     "mkdocs-material ~=9.1",
#     "mkdocstrings[python-legacy] ~=0.20.0",
# ]
testing = [
    "mongomock ~=4.1",
    "pytest ~=7.3",
    "pytest-cov ~=4.0",
]
cli = [
    "DLite-Python ~=0.3.19",
    "typer[all] ~=0.7.0",
]
dev = [
    "pre-commit ~=2.21",
    "pylint ~=2.17",
    "mongomock ~=4.1",
    "pytest ~=7.3",
    "pytest-cov ~=4.0",
    "DLite-Python ~=0.3.19",
    "typer[all] ~=0.7.0",
]

[project.scripts]
entities-service = "dlite_entities_service.utils_cli.main:APP"

[project.urls]
Home = "https://github.com/CasperWA/dlite-entities-service"
Documentation = "https://CasperWA.github.io/dlite-entities-service"
Source = "https://github.com/CasperWA/dlite-entities-service"
"Issue Tracker" = "https://github.com/CasperWA/dlite-entities-service/issues"
Changelog = "https://CasperWA.github.io/dlite-entities-service/latest/CHANGELOG"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
scripts_are_modules = true
warn_unused_configs = true
show_error_codes = true
allow_redefinition = true
check_untyped_defs = true
plugins = ["pydantic.mypy"]

[tool.pylint.messages_control]
max-line-length = 88
disable = [
    "too-few-public-methods",
    "no-name-in-module",
    "no-self-argument",
]
max-args = 15
max-branches = 15

[tool.pytest.ini_options]
minversion = "7.3"
addopts = "-rs --cov=dlite_entities_service --cov-report=term"
filterwarnings = [
    # Remove warning filter once tiangolo/typer#334 is resolved.
    "ignore:.*'autocompletion' is renamed to 'shell_complete'.*:DeprecationWarning",
    "ignore:.*pkg_resources is deprecated as an API.*:DeprecationWarning",
]
